<?php

namespace Modules\Project\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Modules\HR\Models\Employee;

class ProjectCost extends Model
{
    protected $fillable = [
        'project_id',
        'project_budget_id',
        'cost_type',
        'description',
        'notes',
        'amount',
        'cost_date',
        'employee_id',
        'expense_id',
        'hours',
        'hourly_rate',
        'is_billable',
        'is_auto_generated',
        'reference_type',
        'reference_id',
        'created_by',
    ];

    protected $casts = [
        'amount' => 'decimal:2',
        'cost_date' => 'date',
        'hours' => 'decimal:2',
        'hourly_rate' => 'decimal:2',
        'is_billable' => 'boolean',
        'is_auto_generated' => 'boolean',
    ];

    /**
     * Cost types.
     */
    public const COST_TYPES = [
        'labor' => 'Labor',
        'expense' => 'Expense',
        'contractor' => 'Contractor',
        'infrastructure' => 'Infrastructure',
        'software' => 'Software & Licenses',
        'other' => 'Other',
    ];

    /**
     * Cost type colors.
     */
    public const COST_TYPE_COLORS = [
        'labor' => 'primary',
        'expense' => 'info',
        'contractor' => 'warning',
        'infrastructure' => 'secondary',
        'software' => 'success',
        'other' => 'dark',
    ];

    /**
     * Cost type icons.
     */
    public const COST_TYPE_ICONS = [
        'labor' => 'ti-users',
        'expense' => 'ti-receipt',
        'contractor' => 'ti-briefcase',
        'infrastructure' => 'ti-server',
        'software' => 'ti-app-window',
        'other' => 'ti-dots',
    ];

    /**
     * Get the project.
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * Get the budget category.
     */
    public function budget(): BelongsTo
    {
        return $this->belongsTo(ProjectBudget::class, 'project_budget_id');
    }

    /**
     * Get the employee (for labor costs).
     */
    public function employee(): BelongsTo
    {
        return $this->belongsTo(Employee::class);
    }

    /**
     * Get the user who created this cost.
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Get the cost type label.
     */
    public function getCostTypeLabelAttribute(): string
    {
        return self::COST_TYPES[$this->cost_type] ?? ucfirst($this->cost_type);
    }

    /**
     * Get the cost type color.
     */
    public function getCostTypeColorAttribute(): string
    {
        return self::COST_TYPE_COLORS[$this->cost_type] ?? 'secondary';
    }

    /**
     * Get the cost type icon.
     */
    public function getCostTypeIconAttribute(): string
    {
        return self::COST_TYPE_ICONS[$this->cost_type] ?? 'ti-circle';
    }

    /**
     * Scope for billable costs.
     */
    public function scopeBillable($query)
    {
        return $query->where('is_billable', true);
    }

    /**
     * Scope for non-billable costs.
     */
    public function scopeNonBillable($query)
    {
        return $query->where('is_billable', false);
    }

    /**
     * Scope for manual (non-auto-generated) costs.
     */
    public function scopeManual($query)
    {
        return $query->where('is_auto_generated', false);
    }

    /**
     * Scope for auto-generated costs (from worklogs).
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope for date range.
     */
    public function scopeDateRange($query, $startDate, $endDate)
    {
        return $query->whereBetween('cost_date', [$startDate, $endDate]);
    }

    /**
     * Scope by cost type.
     */
    public function scopeOfType($query, $type)
    {
        return $query->where('cost_type', $type);
    }

    /**
     * Boot the model.
     */
    protected static function boot()
    {
        parent::boot();

        // Update budget actual amount when cost is saved
        static::saved(function ($cost) {
            if ($cost->project_budget_id) {
                $cost->budget?->recalculateActual();
            }
        });

        // Update budget actual amount when cost is deleted
        static::deleted(function ($cost) {
            if ($cost->project_budget_id) {
                $cost->budget?->recalculateActual();
            }
        });
    }
}
