<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>{{ $report->name }}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: DejaVu Sans, sans-serif;
      font-size: 10px;
      line-height: 1.4;
      color: #333;
      padding: 20px;
    }

    .header {
      text-align: center;
      margin-bottom: 20px;
      border-bottom: 2px solid #4a90a4;
      padding-bottom: 15px;
    }

    .header h1 {
      font-size: 20px;
      color: #2c3e50;
      margin-bottom: 5px;
    }

    .header .period {
      font-size: 12px;
      color: #7f8c8d;
    }

    .meta-info {
      margin-bottom: 15px;
      font-size: 9px;
      color: #7f8c8d;
    }

    .meta-info table {
      width: 100%;
      border: none;
    }

    .meta-info td {
      border: none;
      padding: 2px 0;
    }

    .project-section {
      margin-bottom: 20px;
      page-break-inside: avoid;
    }

    .project-header {
      background: #f0f0f0;
      padding: 8px 10px;
      border-left: 3px solid #4a90a4;
      margin-bottom: 5px;
    }

    .project-header-table {
      width: 100%;
      border: none;
    }

    .project-header-table td {
      border: none;
      padding: 0;
      vertical-align: middle;
    }

    .project-code {
      background: #4a90a4;
      color: white;
      padding: 2px 6px;
      font-size: 9px;
      font-weight: bold;
    }

    .project-name {
      font-size: 12px;
      font-weight: bold;
      color: #2c3e50;
    }

    .project-summary {
      text-align: right;
      font-size: 9px;
      color: #666;
    }

    table.data-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 5px;
    }

    table.data-table th,
    table.data-table td {
      padding: 6px 8px;
      border: 1px solid #dee2e6;
    }

    table.data-table th {
      background: #f8f9fa;
      font-weight: bold;
      font-size: 9px;
      text-transform: uppercase;
      color: #495057;
      text-align: left;
    }

    table.data-table th.numeric,
    table.data-table td.numeric {
      text-align: right;
    }

    table.data-table .project-total-row {
      background: #f8f9fa;
      font-weight: bold;
    }

    .grand-total {
      margin-top: 20px;
      padding: 15px;
      background: #4a90a4;
      color: white;
      page-break-inside: avoid;
    }

    .grand-total h3 {
      font-size: 14px;
      margin-bottom: 10px;
      border-bottom: 1px solid rgba(255,255,255,0.3);
      padding-bottom: 5px;
    }

    .grand-total-table {
      width: 100%;
      border: none;
    }

    .grand-total-table td {
      border: none;
      padding: 3px 0;
      color: white;
      vertical-align: middle;
    }

    .grand-total-table .label {
      font-size: 10px;
    }

    .grand-total-table .value {
      text-align: right;
      font-size: 12px;
      font-weight: bold;
    }

    .grand-total-table .amount-row .value {
      font-size: 16px;
    }

    .footer {
      margin-top: 30px;
      text-align: center;
      font-size: 8px;
      color: #adb5bd;
      border-top: 1px solid #dee2e6;
      padding-top: 10px;
    }

    .no-print {
      margin-bottom: 20px;
      text-align: right;
    }

    .print-btn {
      background: #4a90a4;
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      cursor: pointer;
      font-size: 14px;
    }

    .print-btn:hover {
      background: #357abd;
    }

    @media print {
      .no-print {
        display: none;
      }
      body {
        padding: 0;
      }
    }
  </style>
</head>
<body>
  @if(!isset($isPdf) || !$isPdf)
  <div class="no-print">
    <button class="print-btn" onclick="window.print()">
      Print Report
    </button>
  </div>
  @endif

  <div class="header">
    <h1>{{ $report->name }}</h1>
    <div class="period">
      {{ $report->start_date->format('F d, Y') }} - {{ $report->end_date->format('F d, Y') }}
    </div>
  </div>

  <div class="meta-info">
    <table>
      <tr>
        <td style="width: 50%">Generated by: {{ $report->createdBy->name ?? 'System' }}</td>
        <td style="width: 50%; text-align: right;">Created: {{ $report->created_at->format('M d, Y H:i') }}</td>
      </tr>
    </table>
  </div>

  @if($report->projects_data)
    @foreach($report->projects_data as $project)
      @php
        $projectAvgRate = $project['total_hours'] > 0 ? $project['total_amount'] / $project['total_hours'] : 0;
      @endphp
      <div class="project-section">
        <div class="project-header">
          <table class="project-header-table">
            <tr>
              <td style="width: 60%">
                <span class="project-code">{{ $project['project_code'] }}</span>
                <span class="project-name">{{ $project['project_name'] }}</span>
              </td>
              <td class="project-summary">
                {{ number_format($project['total_hours'], 2) }} hrs |
                {{ number_format($projectAvgRate, 2) }} EGP/hr |
                {{ number_format($project['total_amount'], 2) }} EGP
              </td>
            </tr>
          </table>
        </div>

        <table class="data-table">
          <thead>
            <tr>
              <th style="width: 30%">Employee</th>
              <th style="width: 15%">Team</th>
              <th style="width: 13%" class="numeric">Hours</th>
              <th style="width: 18%" class="numeric">Rate (EGP/hr)</th>
              <th style="width: 22%" class="numeric">Amount</th>
            </tr>
          </thead>
          <tbody>
            @foreach($project['employees'] as $employee)
              <tr>
                <td>{{ $employee['employee_name'] }}</td>
                <td>{{ $employee['team'] ?? '-' }}</td>
                <td class="numeric">{{ number_format($employee['hours'], 2) }}</td>
                <td class="numeric">{{ number_format($employee['rate'], 2) }}</td>
                <td class="numeric">{{ number_format($employee['amount'], 2) }} EGP</td>
              </tr>
            @endforeach
            <tr class="project-total-row">
              <td colspan="2" style="text-align: right">Project Total:</td>
              <td class="numeric">{{ number_format($project['total_hours'], 2) }}</td>
              <td class="numeric">{{ number_format($projectAvgRate, 2) }} EGP/hr</td>
              <td class="numeric">{{ number_format($project['total_amount'], 2) }} EGP</td>
            </tr>
          </tbody>
        </table>
      </div>
    @endforeach
  @endif

  @php
    // Calculate team totals
    $teamTotals = [];
    $teams = \Modules\HR\Models\Employee::TEAMS;
    foreach ($teams as $teamKey => $teamLabel) {
      $teamTotals[$teamKey] = ['hours' => 0, 'amount' => 0, 'label' => $teamLabel];
    }
    $teamTotals[''] = ['hours' => 0, 'amount' => 0, 'label' => 'Unassigned'];

    if ($report->projects_data) {
      foreach ($report->projects_data as $project) {
        foreach ($project['employees'] as $employee) {
          $team = $employee['team'] ?? '';
          if (isset($teamTotals[$team])) {
            $teamTotals[$team]['hours'] += $employee['hours'];
            $teamTotals[$team]['amount'] += $employee['amount'];
          }
        }
      }
    }

    $grandAvgRate = $report->total_hours > 0 ? $report->total_amount / $report->total_hours : 0;
  @endphp

  <!-- Team Summary -->
  <div class="project-section">
    <div class="project-header">
      <table class="project-header-table">
        <tr>
          <td>
            <span class="project-name">Summary by Team</span>
          </td>
        </tr>
      </table>
    </div>

    <table class="data-table">
      <thead>
        <tr>
          <th style="width: 40%">Team</th>
          <th style="width: 30%" class="numeric">Hours</th>
          <th style="width: 30%" class="numeric">Amount (EGP)</th>
        </tr>
      </thead>
      <tbody>
        @foreach($teamTotals as $teamKey => $teamData)
          @if($teamData['hours'] > 0 || $teamKey === '')
            <tr>
              <td>@if($teamKey === '')<em>{{ $teamData['label'] }}</em>@else{{ $teamData['label'] }}@endif</td>
              <td class="numeric">{{ number_format($teamData['hours'], 2) }}</td>
              <td class="numeric">{{ number_format($teamData['amount'], 2) }}</td>
            </tr>
          @endif
        @endforeach
      </tbody>
    </table>
  </div>

  <div class="grand-total">
    <h3>Grand Total</h3>
    <table class="grand-total-table">
      <tr>
        <td class="label">Total Hours:</td>
        <td class="value">{{ number_format($report->total_hours, 2) }} hours</td>
      </tr>
      <tr>
        <td class="label">Average Rate:</td>
        <td class="value">{{ number_format($grandAvgRate, 2) }} EGP/hr</td>
      </tr>
      <tr class="amount-row">
        <td class="label">Total Amount:</td>
        <td class="value">{{ number_format($report->total_amount, 2) }} EGP</td>
      </tr>
    </table>
  </div>

  <div class="footer">
    Generated from Aura HR Management System | {{ now()->format('M d, Y H:i') }}
  </div>
</body>
</html>
